/**
 * [INPUT]: 依赖 @/lib/locale 的 Locale 类型，承载 app shell、background audio、login、workspace、record 的本地化文案字典。
 * [OUTPUT]: 对外提供 copy 字典、getCopy 与按 locale 取值的辅助类型。
 * [POS]: lib 的文案真相源，集中管理页面可见文本、顶栏邮件复制反馈、背景音乐播放/暂停/拦截语义、OCR/编辑/新病历动作、BMI 标签、病程资料空态与重试按钮文案，禁止组件继续内联双语字符串。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import type { Locale } from '@/lib/locale'

type LocaleText = Record<Locale, string>

function text(zh: string, en: string): LocaleText {
  return { zh, en }
}

export const copy = {
  app: {
    boot: {
      status: text('会话恢复', 'Session Restore'),
      title: text('正在恢复访问状态', 'Restoring session access'),
    },
    userLabel: {
      anonymous: text('匿名会话', 'Anonymous Session'),
      authenticated: text('认证会话', 'Authenticated Session'),
    },
  },
  models: {
    title: text('模型配置', 'Model Settings'),
    eyebrow: text('模型', 'Models'),
    catalogTitle: text('默认模型目录', 'Default model catalog'),
    catalogDescription: text(
      '文字与图像链路各自绑定一个默认模型；图像链路负责病历/检验报告 OCR，文字链路负责结构化提取与对话式修改。',
      'Text and image pipelines each bind one default model. Images power record/lab OCR; text powers structured extraction and conversational editing.',
    ),
    modalityText: text('文字', 'Text'),
    modalityImage: text('图像', 'Image'),
    modalityBadgeText: text('文本输入', 'text input'),
    modalityBadgeImage: text('图像输入', 'image input'),
    providerTitle: text('自带密钥', 'Bring your own key'),
    providerDescription: text(
      '保存自己的 provider 密钥后，文字链路将优先使用它；密钥服务端加密存储，永不回读明文。',
      'Save your own provider key and the text pipeline will prefer it. Keys are encrypted server-side and never returned.',
    ),
  },
  authFeedback: {
    missingEnv: text('缺少 Supabase 环境变量，当前无法完成认证。', 'Supabase environment variables are missing; authentication is unavailable.'),
    missingEnvAnonymous: text('缺少 Supabase 环境变量，当前无法进入匿名模式。', 'Supabase environment variables are missing; anonymous sessions are unavailable.'),
    missingEnvGoogle: text('缺少 Supabase 环境变量，当前无法使用 Google 登录。', 'Supabase environment variables are missing; Google sign-in is unavailable.'),
    resetFailed: text('暂时无法发送重置邮件，请稍后再试。', 'Could not send the reset email right now. Retry later.'),
    resetSent: text('如果该邮箱已注册，我们会发送重置邮件。', 'If that email is registered, we will send a reset link.'),
    invalidCredentials: text('邮箱或密码错误，请重新确认后再试。', 'Email or password is incorrect. Please double-check and retry.'),
    signingIn: text('认证成功，正在进入工作区。', 'Authenticated. Entering the workspace.'),
    signUpFailed: text('暂时无法完成注册，请稍后再试。', 'Could not complete sign-up right now. Retry later.'),
    signUpSuccess: text('注册成功，正在进入工作区。', 'Signed up. Entering the workspace.'),
    signUpPending: text('注册请求已提交，请查收确认邮件后登录。', 'Sign-up submitted. Check your email to confirm your account, then sign in.'),
    anonymousFailed: text('匿名入口暂时不可用，请稍后再试。', 'Anonymous access is unavailable right now. Retry later.'),
    anonymousReady: text('匿名会话已建立，正在进入工作区。', 'Anonymous session created. Entering the workspace.'),
    googleFailed: text('Google 登录暂时不可用，请稍后再试。', 'Google sign-in is unavailable right now. Retry later.'),
    googlePending: text('正在前往 Google 登录。', 'Redirecting to Google sign-in.'),
    serviceUnavailable: text('认证服务暂时不可用，请稍后再试。', 'The auth service is unavailable right now. Retry later.'),
    restoreFailed: text('无法恢复登录状态，请刷新后重试。', 'Could not restore the session. Refresh and retry.'),
    callbackInvalid: text('登录回调已失效，请重新登录。', 'The auth callback expired. Sign in again.'),
    signOutFailed: text('退出失败，请稍后再试。', 'Sign-out failed. Retry later.'),
    callbackUnavailable: text('认证回调暂时不可用，请重新请求链接或重试登录。', 'The auth callback is unavailable. Request a new link or try signing in again.'),
    callbackMissingEnv: text('缺少 Supabase 环境变量，当前无法完成认证。', 'Supabase environment variables are missing; authentication cannot complete.'),
    resetLinkInvalid: text('重置链接无效或已过期，请重新请求重置邮件。', 'The reset link is invalid or expired. Request a new reset email.'),
    resetTitle: text('设置新密码', 'Set a new password'),
    resetEmail: text('当前邮箱', 'Email'),
    newPassword: text('新密码', 'New password'),
    confirmPassword: text('确认新密码', 'Confirm new password'),
    passwordMismatch: text('两次输入的密码不一致。', 'The passwords do not match.'),
    passwordTooShort: text('密码至少需要 6 个字符。', 'Use at least 6 characters for your password.'),
    passwordSave: text('保存新密码', 'Save new password'),
    passwordSaving: text('正在保存…', 'Saving…'),
    passwordSaved: text('密码已更新。', 'Your password has been updated.'),
    passwordSaveFailed: text('未能更新密码，请重试；链接过期时请重新请求邮件。', 'Could not update the password. Retry, or request a new email if the link expired.'),
    resetRequestAgain: text('重新请求重置邮件', 'Request a new reset email'),
    backToLogin: text('返回登录', 'Back to sign-in'),
    continueToDashboard: text('进入总览', 'Go to dashboard'),
    callbackRestoring: text('正在恢复登录状态', 'Restoring your session'),
  },
  privacyGate: {
    darkEyebrow: text('入场须知', 'Privacy Notice'),
    darkHeading: text('在进入系统前，请先确认数据使用说明', 'Before entering, confirm how your data is used'),
    darkAccept: text('我已了解并继续', 'Understood, continue'),
    darkDecline: text('暂不继续', 'Not now'),
    lightEyebrow: text('入场须知', 'Privacy Notice'),
    lightHeading: text('在开始之前，请确认隐私与用途边界', 'Before we start, confirm the privacy boundary'),
    lightAccept: text('同意并继续', 'Agree and continue'),
    lightDecline: text('暂不进入', 'Not now'),
    fullPolicy: text('查看完整隐私条款', 'View the full privacy policy'),
  },
  dashboard: {
    title: text('数据总览', 'Dashboard'),
    eyebrow: text('总览', 'Overview'),
    statRecords: text('病历总数', 'Records'),
    statReadings: text('实验室读数', 'Lab readings'),
    statShares: text('活跃分享', 'Active shares'),
    statAiCalls: text('近 30 天 AI 分析', 'AI analyses · 30d'),
    recordsTitle: text('我的病历', 'My records'),
    recordNameMissing: text('未填写姓名', 'Name not entered'),
    recordTumorTypeMissing: text('未填写病种', 'Diagnosis not entered'),
    recordsLoading: text('正在读取病历…', 'Loading records…'),
    recordsLoadMore: text('加载更多病历', 'Load more records'),
    recordsLoadFailed: text('病历读取失败，请重试。', 'Could not load records. Please retry.'),
    recordsMoreFailed: text('更多病历暂时无法读取，已加载的病历仍可使用。', 'Could not load more records. The records already shown are still available.'),
    recordsRetry: text('重新读取病历', 'Retry loading records'),
    continueIntake: text('继续录入', 'Continue intake'),
    tumorTypeLabel: text('癌种', 'Tumor type'),
    tumorTypeMissing: text('待补充', 'Missing'),
    abnormalTitle: text('最近异常读数', 'Recent abnormal readings'),
    abnormalEmpty: text('暂无异常读数，保持监测。', 'No abnormal readings. Keep monitoring.'),
    highLabel: text('偏高', 'High'),
    lowLabel: text('偏低', 'Low'),
    viewRecord: text('查看病历', 'View record'),
    viewAnalytics: text('查看指标', 'View analytics'),
    emptyHeading: text('从第一份病历开始', 'Start with your first record'),
    emptyDescription: text(
      '还没有病历。把治疗经过或检验报告粘贴到工作台，一次结构化提取即可生成可追溯的一页档案。',
      'No records yet. Paste a treatment history or lab report into the workspace; one structured extraction builds a traceable one-page record.',
    ),
    emptyAction: text('前往工作台', 'Go to workspace'),
    loadFailed: text('总览数据读取失败，请检查网络后重试。', 'Could not load dashboard data. Check your network and retry.'),
    updatedLabel: text('更新于', 'Updated'),
    recentSideEffectsTitle: text('最近副作用', 'Recent side effects'),
    visitDue: text('已逾期', 'Overdue'),
    recentSideEffectsEmpty: text('还没有症状记录。', 'No symptom entries yet.'),
    viewSideEffects: text('全部记录', 'View all'),
    sectionUnavailable: text('这部分数据暂时无法读取。', 'This section could not be loaded.'),
    visitToday: text('今天复查', 'Visit today'),
    nextStepsTitle: text('接下来可以做什么', 'What you can do next'),
    nextStepsRecord: text('整理治疗经过，生成病历和时间线。', 'Organize treatment history into a record and timeline.'),
    nextStepsSymptoms: text('在病历中记录症状，并关联对应的治疗线。', 'Log symptoms in a record and link them to treatment lines.'),
    nextStepsVisits: text('保存随访和下次安排，复诊前生成摘要。', 'Save visits and next steps, then prepare a visit summary.'),
    quickActions: text('继续这份病历', 'Continue this record'),
  },
  clinicalWorkflow: {
    navigation: text('当前病历导航', 'Current record navigation'),
    record: text('病历', 'Record'),
    labs: text('指标', 'Lab trends'),
    symptoms: text('症状', 'Symptoms'),
    followUp: text('随访', 'Follow-up'),
    loading: text('正在读取记录…', 'Loading records…'),
    recordUnavailable: text('无法读取这份病历，请重试或返回工作台。', 'This record could not be loaded. Retry or return to the workspace.'),
    retry: text('重新读取', 'Retry'),
    editVisit: text('编辑随访', 'Edit visit'),
    editSymptom: text('编辑症状记录', 'Edit symptom entry'),
    invalidDate: text('请填写有效的日期，结束或下次日期不能早于开始日期。', 'Enter valid dates. The end or next date cannot precede the start date.'),
    symptomRequired: text('请填写症状名称。', 'Enter a symptom name.'),
    symptomPresets: text('选择常见症状', 'Choose a common symptom'),
    deleteTitle: text('删除这条记录？', 'Delete this entry?'),
    deleteDescription: text('删除后无法撤销。其他记录会保留。', 'This cannot be undone. Other records will be kept.'),
    deleteConfirm: text('确认删除', 'Delete entry'),
    deleting: text('删除中…', 'Deleting…'),
    deleted: text('记录已删除', 'Entry deleted'),
    savedStatus: text('正在更新随访状态…', 'Updating follow-up status…'),
    summaryUnavailable: text('摘要所需的数据尚未完整读取，请先重试。', 'Load all records before generating a summary.'),
    copyFailed: text('复制失败，请手动选择摘要文字复制。', 'Copy failed. Select and copy the summary text manually.'),
  },
  errorBoundary: {
    status: text('页面异常', 'Unexpected Error'),
    title: text('页面出现了一点问题', 'Something went wrong'),
    description: text(
      '渲染过程发生错误，重新加载即可恢复；你的数据安全地保存在服务端。',
      'A rendering error occurred. Reload to recover; your data stays safe on the server.',
    ),
    action: text('重新加载', 'Reload'),
    detail: text('错误详情', 'Error details'),
  },
  followUp: {
    title: text('随访记录', 'Follow-up Visits'),
    eyebrow: text('随访', 'Follow-up'),
    description: text(
      '把每次就诊的时间、地点、结论和下次安排留档，随访时不再靠回忆。',
      'Keep every visit\'s time, place, conclusion and next steps on file — no more relying on memory.',
    ),
    statusLabel: text('随访状态', 'Follow-up status'),
    statusTreating: text('治疗中', 'Treating'),
    statusPaused: text('暂停', 'Paused'),
    statusCompleted: text('结疗', 'Completed'),
    statusLost: text('失访', 'Lost contact'),
    statusAuto: text('自动（按治疗线推断）', 'Auto (derived from lines)'),
    statusSavedFeedback: text('随访状态已更新', 'Follow-up status updated'),
    formTitle: text('新增随访', 'New visit'),
    visitedOnLabel: text('就诊日期', 'Visit date'),
    locationLabel: text('地点（可选）', 'Location (optional)'),
    locationPlaceholder: text('如：肿瘤医院门诊', 'e.g. oncology outpatient clinic'),
    doctorLabel: text('医生（可选）', 'Doctor (optional)'),
    conclusionLabel: text('结论 / 备注', 'Conclusion / notes'),
    nextPlanLabel: text('下次安排', 'Next steps'),
    nextVisitOnLabel: text('下次复查日期', 'Next visit date'),
    saveButton: text('保存随访', 'Save visit'),
    savingButton: text('保存中…', 'Saving…'),
    savedFeedback: text('已记录', 'Logged'),
    saveFailedFeedback: text('保存失败，请检查网络后重试', 'Could not save. Check your network and retry'),
    editButton: text('编辑', 'Edit'),
    cancelButton: text('取消', 'Cancel'),
    deleteButton: text('删除', 'Delete'),
    deleteFailedFeedback: text('删除失败，请稍后重试', 'Could not delete. Retry later'),
    empty: text('还没有随访记录。每次就诊后随手记一条。', 'No visits logged yet. Add one after each appointment.'),
    loadFailedFeedback: text('随访记录读取失败，请检查网络后重试。', 'Could not load follow-up visits. Check your network and retry.'),
    openFromRecord: text('随访', 'Follow-up'),
    backToRecord: text('返回病历', 'Back to record'),
    nextVisitPrefix: text('下次复查', 'Next visit'),
    lastVisitPrefix: text('上次随访', 'Last visit'),
    daysUntil: text('天后', 'days away'),
    daysOverdue: text('天前已到期待复查', 'days since due'),
  },
  sideEffects: {
    title: text('副作用记录', 'Side-effect Log'),
    eyebrow: text('症状日志', 'Symptom log'),
    description: text(
      '记录治疗过程中的身体反应，就诊时作为辅助说明。非诊断工具，急症请立即就医。',
      'Log how your body responds to treatment and share it at visits. This is not a diagnostic tool; seek care immediately for emergencies.',
    ),
    formTitle: text('新增记录', 'New entry'),
    symptomLabel: text('症状', 'Symptom'),
    symptomPlaceholder: text('如：恶心、乏力、手脚麻木', 'e.g. nausea, fatigue, numb hands'),
    severityLabel: text('严重程度', 'Severity'),
    severityMild: text('轻度', 'Mild'),
    severityModerate: text('中度', 'Moderate'),
    severitySevere: text('重度', 'Severe'),
    dateLabel: text('发生日期', 'Start date'),
    resolvedLabel: text('缓解日期（可选）', 'Resolved date (optional)'),
    lineLabel: text('关联治疗线（可选）', 'Related treatment line (optional)'),
    lineNone: text('不关联', 'Not attributed'),
    medicationLabel: text('处理方式（可选）', 'Action taken (optional)'),
    medicationPlaceholder: text('如：自行服用止吐药、告知医生', 'e.g. took anti-nausea medication, told the doctor'),
    notesLabel: text('备注（可选）', 'Notes (optional)'),
    saveButton: text('保存记录', 'Save entry'),
    savingButton: text('保存中…', 'Saving…'),
    savedFeedback: text('已记录', 'Logged'),
    saveFailedFeedback: text('保存失败，请检查网络后重试', 'Could not save. Check your network and retry'),
    editButton: text('编辑', 'Edit'),
    cancelButton: text('取消', 'Cancel'),
    deleteButton: text('删除', 'Delete'),
    deleteFailedFeedback: text('删除失败，请稍后重试', 'Could not delete. Retry later'),
    empty: text('还没有记录。出现不适时随手记一条，复诊时更好回忆。', 'No entries yet. Jot symptoms down as they happen; easier to recall at visits.'),
    loadFailedFeedback: text('副作用记录读取失败，请检查网络后重试。', 'Could not load side-effect records. Check your network and retry.'),
    openFromRecord: text('副作用记录', 'Side-effect log'),
    backToRecord: text('返回病历', 'Back to record'),
    ongoing: text('未缓解', 'Ongoing'),
    overdueBadge: text('超过 7 天未缓解', 'Ongoing for 7+ days'),
    customGroup: text('我的常用', 'My common'),
    summaryTitle: text('复诊摘要', 'Visit summary'),
    summaryDescription: text(
      '选择日期范围，生成一段可以直接给医生看的文字。',
      'Pick a date range and generate text you can hand straight to your doctor.',
    ),
    summaryFrom: text('开始日期', 'From'),
    summaryTo: text('结束日期', 'To'),
    summaryGenerate: text('生成摘要', 'Generate summary'),
    summaryCopy: text('复制摘要', 'Copy summary'),
    summaryCopied: text('摘要已复制', 'Summary copied'),
    summaryEmpty: text('这个时间范围没有记录。', 'No entries in this range.'),
    summaryHeader: text('复诊摘要', 'Visit summary'),
    symptomGroups: [
      {
        label: text('消化', 'Digestive'),
        items: [
          text('恶心', 'Nausea'),
          text('呕吐', 'Vomiting'),
          text('腹泻', 'Diarrhea'),
          text('便秘', 'Constipation'),
          text('口腔溃疡', 'Mouth sores'),
          text('食欲下降', 'Appetite loss'),
          text('味觉改变', 'Taste changes'),
        ],
      },
      {
        label: text('全身', 'Whole body'),
        items: [
          text('乏力', 'Fatigue'),
          text('发热', 'Fever'),
          text('盗汗', 'Night sweats'),
          text('体重下降', 'Weight loss'),
        ],
      },
      {
        label: text('血液', 'Blood'),
        items: [
          text('白细胞降低', 'Low white cells'),
          text('贫血', 'Anemia'),
          text('血小板降低', 'Low platelets'),
        ],
      },
      {
        label: text('皮肤毛发', 'Skin & hair'),
        items: [
          text('脱发', 'Hair loss'),
          text('皮疹', 'Rash'),
          text('瘙痒', 'Itching'),
          text('手足综合征', 'Hand-foot syndrome'),
        ],
      },
      {
        label: text('神经', 'Neuro'),
        items: [
          text('手脚麻木', 'Numb hands/feet'),
          text('头痛', 'Headache'),
          text('头晕', 'Dizziness'),
          text('失眠', 'Insomnia'),
          text('记忆力下降', 'Memory lapses'),
        ],
      },
      {
        label: text('情绪', 'Mood'),
        items: [
          text('情绪低落', 'Low mood'),
          text('焦虑', 'Anxiety'),
        ],
      },
      {
        label: text('其他', 'Other'),
        items: [
          text('咳嗽', 'Cough'),
          text('气短', 'Short of breath'),
          text('水肿', 'Swelling'),
          text('肌肉关节痛', 'Muscle/joint pain'),
        ],
      },
    ],
  },
  donate: {
    title: text('支持萤屿', 'Support Firefly Isle'),
    eyebrow: text('公益项目', 'Public project'),
    description: text(
      '一页萤屿是公益项目，全部功能免费。捐赠完全自愿，不解锁任何能力，只用来维持服务器与模型调用。',
      'Firefly Isle is a public project. Every feature stays free. Donations are voluntary and never unlock extra capabilities; they only keep hosting and model calls running.',
    ),
    amountLabel: text('选择金额', 'Choose an amount'),
    customLabel: text('自定义（美元）', 'Custom (USD)'),
    customPlaceholder: text('例如 8', 'e.g. 8'),
    action: text('去捐赠', 'Donate'),
    submitting: text('正在打开支付…', 'Opening checkout…'),
    disabled: text('捐赠通道尚未配置 Stripe 密钥，当前只展示说明。', 'Donation checkout is not configured yet. This page is informational until Stripe keys are set.'),
    failed: text('无法打开捐赠页面，请稍后重试。', 'Could not open donation checkout. Retry later.'),
    note: text('支付由 Stripe 处理。完成后你会回到设置页，功能不会改变。', 'Payments are processed by Stripe. You return to settings afterwards; product features do not change.'),
  },
  settings: {
    title: text('账户设置', 'Account Settings'),
    accountSection: text('账户', 'Account'),
    emailLabel: text('登录邮箱', 'Email'),
    anonymousLabel: text('匿名会话', 'Anonymous Session'),
    profileSection: text('个人资料', 'Profile'),
    displayNameLabel: text('显示名称', 'Display name'),
    displayNamePlaceholder: text('输入显示名称', 'Enter a display name'),
    localeLabel: text('界面语言', 'Interface language'),
    themeLabel: text('外观主题', 'Appearance'),
    accentLabel: text('强调色', 'Accent'),
    donateSection: text('支持萤屿', 'Support'),
    donateLink: text('打开捐赠页', 'Open donation page'),
    saveButton: text('保存资料', 'Save Profile'),
    savingButton: text('保存中…', 'Saving…'),
    savedFeedback: text('设置已保存', 'Settings saved'),
    saveFailedFeedback: text('保存失败，请检查网络后重试', 'Could not save settings. Check your network and retry'),
    loadFailedFeedback: text('账户设置读取失败，本地偏好仍可使用', 'Could not load account settings. Local preferences stay active'),
    profileUnavailable: text('档案服务尚未启用，偏好将只保存在本机', 'Profile service is not enabled yet; preferences stay on this device'),
    privacySection: text('数据与隐私', 'Data & Privacy'),
    exportDescription: text(
      '将你的病历、治疗线、化验、症状、随访、分享、用量、捐赠与账户设置打包为 JSON 下载到本机，不含服务密钥。',
      'Download records, treatment lines, labs, symptoms, follow-ups, shares, usage, donations and account settings as JSON, excluding service keys.',
    ),
    exportButton: text('导出我的数据', 'Export My Data'),
    exportingButton: text('导出中…', 'Exporting…'),
    exportFailedFeedback: text('导出失败，请联网后重试', 'Export failed. Reconnect and retry'),
    deleteDescription: text(
      '删除账户将永久清除病历、化验、症状、随访、分享与账户档案，无法撤销。捐赠收据移除账户关联后保留。',
      'Deleting your account permanently removes records, labs, symptoms, follow-ups, shares and profile. This cannot be undone. Donation receipts are retained without their account association.',
    ),
    deleteConfirmLabel: text('输入「删除」以确认', 'Type DELETE to confirm'),
    deleteConfirmWord: text('删除', 'DELETE'),
    deleteButton: text('删除账户', 'Delete Account'),
    deletingButton: text('删除中…', 'Deleting…'),
    deleteFailedFeedback: text('删除失败，请稍后重试', 'Could not delete account. Retry later'),
    deleteConfirmMismatch: text('确认词不匹配', 'Confirmation does not match'),
  },
  localeToggle: {
    zh: text('中文', 'Chinese'),
    en: text('英文', 'English'),
  },
  themeToggle: {
    dark: text('深色', 'Dark'),
    light: text('浅色', 'Light'),
  },
  backgroundAudio: {
    control: text('音乐', 'Music'),
    next: text('下一首背景音乐', 'Next background track'),
    previous: text('上一首背景音乐', 'Previous background track'),
    track: text('当前曲目', 'Current track'),
    aria: {
      blocked: text('浏览器已阻止自动播放，点击播放背景音乐', 'Browser blocked autoplay. Click to play background music'),
      idle: text('背景音乐已开启，点击暂停', 'Background music is on. Click to pause'),
      loading: text('背景音乐加载中，点击暂停', 'Background music is loading. Click to pause'),
      paused: text('背景音乐已暂停，点击继续播放', 'Background music is paused. Click to continue'),
      playing: text('背景音乐播放中，点击暂停', 'Background music is playing. Click to pause'),
      unavailable: text('背景音乐不可用', 'Background music unavailable'),
    },
  },
  shell: {
    brand: {
      darkHeader: text('档案系统 V1', 'Archive System V1'),
      darkTitle: text('一页萤屿', 'Firefly Isle'),
      darkSubtitle: text('临床 AI 控制台', 'Clinical AI Console'),
      lightTitle: text('一页萤屿', 'Firefly Isle'),
      lightSubtitle: text('临床 AI 工作台', 'Clinical AI Workspace'),
    },
    topbar: {
      volume: text('第 01 卷 · 第 52 期', 'VOL. 01 — NO. 52'),
      workspace: text('临床 AI 工作台', 'Clinical AI Workspace'),
      established: text('创立于 2024', 'EST. 2024'),
      contact: {
        label: text('联系我', 'Contact'),
        title: text('联系方式', 'Contact'),
        copyEmail: text('复制邮箱', 'Copy email'),
        copied: text('已复制', 'Copied'),
      },
    },
    nav: {
      extract: text('提取', 'Extract'),
      record: text('病历', 'Record'),
      analytics: text('统计', 'Analytics'),
      dashboard: text('总览', 'Overview'),
      models: text('模型', 'Models'),
      donate: text('捐赠', 'Donate'),
      settings: text('设置', 'Settings'),
      extractFirst: text('先提取', 'Extract first'),
      comingSoon: text('敬请期待', 'Coming Soon'),
      languageToggle: text('语言', 'Language'),
      newExtraction: text('新建提取', 'New Extraction'),
      themeToggle: text('主题', 'Theme'),
      signOut: text('退出登录', 'Sign Out'),
      signingOut: text('会话结束中', 'Ending Session'),
      userProfile: text('用户资料', 'User Profile'),
      pendingAccess: text('访问待定', 'Access Pending'),
      avatarAlt: text('用户头像', 'User Avatar'),
    },
  },
  login: {
    footer: {
      copyrightDark: text('© 2024 一页萤屿档案', '© 2024 Firefly Isle Archive'),
      secureLink: text('安全链路已激活', 'Secure Link Active'),
      copyrightLight: text('© 2024 一页萤屿档案系统', '© 2024 Firefly Isle Archive System'),
      privacyPolicy: text('隐私政策', 'Privacy Policy'),
      systemStatus: text('系统状态', 'System Status'),
      supportCluster: text('支持集群', 'Support Cluster'),
      fullPrivacy: text('查看完整隐私条款', 'Read full privacy policy'),
    },
    hero: {
      badge: text('临床 AI 智能引擎', 'Clinical AI Intelligence'),
      titleLine1: text('把复杂治疗史', 'Turn complex treatment history'),
      titleLine2: text('整理成', 'into'),
      titleAccent: text('一页纸', 'one page'),
      subtitle: text('临床精密性的本质在于对复杂信息的降维与提取。', 'Clinical precision begins with compressing and extracting complex information.'),
      ready: text('系统已就绪，可开始分析', 'System ready for analysis'),
    },
    auth: {
      heading: text('身份访问控制台', 'Access Console'),
      authentication: text('身份验证', 'Authentication'),
      login: text('登录', 'Login'),
      signup: text('注册', 'Sign Up'),
      submitLogin: text('验证并进入控制台', 'Verify and enter console'),
      submitSignup: text('创建账户并登录', 'Create account and log in'),
      submitLoginLight: text('验证并进入系统', 'Verify and enter system'),
      dividerLogin: text('或使用邮箱凭证', 'Or use email credentials'),
      dividerSignup: text('邮箱建档入口', 'Create account with email'),
      thirdPartyAuth: text('第三方鉴权', 'Third-party authentication'),
      wechat: text('微信', 'WeChat'),
      google: text('Google', 'Google'),
      emailLabel: text('注册邮箱', 'Registered Email'),
      emailLabelLight: text('电子邮箱', 'Electronic Mail'),
      emailPlaceholder: text('输入临床邮箱', 'Enter clinical email'),
      emailPlaceholderLight: text('输入邮箱地址', 'Enter email address'),
      passwordLabel: text('加密密钥', 'Encryption Key'),
      passwordLabelLight: text('密码', 'Password'),
      passwordPlaceholder: text('输入 256 位加密密钥', 'Enter 256-bit encryption key'),
      passwordPlaceholderLight: text('••••••••', '••••••••'),
      anonymous: text('无需登录，直接使用匿名会话', 'Use anonymous session without signing in'),
      footerPrivacyPrefix: text('继续即表示你同意', 'By continuing, you agree to the'),
      footerPrivacyLink: text('隐私政策', 'Privacy Policy'),
      secureGateway: text('身份访问管理', 'Identity Access Management'),
      secureGatewayDetail: text('安全网关', 'Secure Gateway'),
    },
    lightHero: {
      titleLine1: text('把复杂治疗史', 'Turn complex treatment history'),
      titleLine2: text('整理成一页纸', 'into one page'),
      body: text('在数字化医疗的洪流中，信息的碎片化成为了精准诊疗的阻碍。一页萤屿利用先进的语义提取引擎，将跨度数年的电子病历、检验报告及主观叙述，浓缩为具备高度逻辑性的临床全景。我们不只是在整理数据，更是在重构生命叙事。', 'In digital medicine, fragmented information blocks precise care. Firefly Isle uses semantic extraction to condense years of records, lab reports, and narratives into a coherent clinical panorama. We do not just organize data; we reconstruct the patient story.'),
      precisionTag: text('精度 // 01', 'Precision // 01'),
      precisionTitle: text('结构化重塑', 'Structured Remodeling'),
      precisionBody: text('自动识别 140 余种临床实体，将非结构化文本转化为标准医学图谱。', 'Automatically identifies more than 140 clinical entities and converts unstructured text into a standardized medical graph.'),
      intelligenceTag: text('智能 // 02', 'Intelligence // 02'),
      intelligenceTitle: text('时间轴推理', 'Timeline Reasoning'),
      intelligenceBody: text('跨时空对比关键指标变化，自动勾勒病情进展与治疗反应曲线。', 'Compares key indicators across time and automatically maps disease progression and treatment response.'),
      certification: text('临床数据加密标准 ISO-27001 认证', 'Clinical Data Encryption Standard ISO-27001 Certified'),
    },
    stats: {
      uptime: text('运行时间', 'Uptime'),
      usersOnline: text('在线用户', 'Users Online'),
    },
  },
  workspace: {
    composer: {
      inputLabel: text('病史输入', 'Patient History Input'),
      inputPlaceholder: text('请描述患者的病情及治疗历程...', 'Describe the patient condition and treatment history...'),
      importRecordFile: text('上传病历 / 检验报告', 'Upload record / lab report'),
      voiceInput: text('语音输入', 'Voice input'),
      extract: text('开始结构化提取', 'Start Structured Extraction'),
      extracting: text('提取中…', 'Extracting…'),
      applyEdit: text('应用病历修改', 'Apply Record Edit'),
      editing: text('修改中…', 'Editing…'),
      extractAsNew: text('作为新病历提取', 'Extract as New Record'),
      editSaved: text('病历修改已保存', 'Record edit saved'),
      retryInitial: text('重试提取', 'Retry Extraction'),
      retryFollowUp: text('重试这轮补充', 'Retry Follow-up'),
      retryEdit: text('重试修改', 'Retry Edit'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      exportPdfLoading: text('导出 PDF 中…', 'Exporting PDF…'),
      exportPng: text('导出 PNG', 'Export PNG'),
      exportPngLoading: text('导出 PNG 中…', 'Exporting PNG…'),
      saving: text('保存中…', 'Saving…'),
      processing: text('处理中…', 'Processing…'),
      followUps: text('最多 3 轮', 'Up to 3 rounds'),
      model: text('模型', 'Model'),
      missing: text('缺失字段', 'Missing'),
      instructionalTitle: text('使用说明', 'Instructions'),
      instructionalBody: text('先输入完整病史，再根据追问一次性补充缺失的临床关键字段。当前仅对肿瘤类型、分期与治疗方案触发追问。', 'Start with a complete patient history, then answer follow-up prompts in one pass to fill critical clinical gaps. Follow-ups currently target tumor type, stage, and regimen only.'),
      currentParameters: text('当前参数', 'Current Parameters'),
      textInput: text('文字输入', 'Text Input'),
      ready: text('准备分析', 'Ready to Analyze'),
      analyzing: text('分析中', 'Analyzing'),
      voice: text('语音录入', 'Voice Input'),
      holdToRecord: text('按住录音', 'Hold to Record'),
      sessionId: text('会话编号：AI-2949-01', 'Session ID: AI-2949-01'),
      location: text('地点：上海诊室', 'Location: Shanghai Clinic'),
      date: text('日期：2024.05.20', 'Date: 2024.05.20'),
      extractor: text('提取器', 'Extractor'),
      gemini: text('Gemini', 'Gemini'),
    },
    followUp: {
      title: text('补充追问', 'Follow-up'),
      placeholder: text('一次性补充缺失信息...', 'Fill in the missing information in one pass...'),
      submit: text('提交补充', 'Submit Follow-up'),
    },
    report: {
      title: text('临床结构化报告', 'Structured Clinical Report'),
      generatedBy: text('由一页萤屿 AI 档案系统生成', 'Generated by Firefly Isle AI Archive'),
      reportId: text('报告编号：实时草稿', 'Report ID: Live Draft'),
      missingPrefix: text('缺失字段：', 'Missing Fields: '),
      disclaimer: text('声明：本报告由人工智能辅助系统自动提取，仅供医疗专业人士参考。最终诊断需结合原始影像及病理报告。', 'Disclaimer: This report is automatically extracted by an AI-assisted system for medical professionals only. Final diagnosis must be confirmed against original imaging and pathology reports.'),
      verifyQr: text('扫码验证报告', 'Scan to verify report'),
      clinicalNotes: text('临床备注', 'Clinical Notes'),
      missingFields: text('仍待补充：', 'Still missing: '),
      completed: text('关键临床字段已补齐，可进入下一阶段渲染。', 'Critical clinical fields are complete and ready for the next stage.'),
      verifiedBy: text('AI 助手已校验', 'Verified by AI Agent'),
      followUpsUsed: text('已使用追问轮次：', 'Follow-ups used: '),
      footerBrand: text('墨迹与档案', 'Ink & Archive'),
      footerProtocol: text('协议：临床 ALPHA-01 // 无未匹配数据', 'Protocol: Clinical ALPHA-01 // No unmatched data'),
      engineLabel: text('临床智能引擎', 'Clinical Intelligence Engine'),
    },
    errors: {
      exportPdf: text('PDF 导出失败，请稍后重试。', 'PDF export failed. Please try again later.'),
      exportPng: text('PNG 导出失败，请稍后重试。', 'PNG export failed. Please try again later.'),
      loadLatest: text('无法恢复最近一次患者记录，请刷新后重试。', 'Could not restore the latest patient record. Please refresh and try again.'),
      missingInput: text('请先输入病情描述，再开始提取。', 'Enter the patient history before starting extraction.'),
      savePatient: text('患者记录保存失败，请稍后重试。', 'Saving the patient record failed. Please try again later.'),
      saveTreatmentLine: text('治疗线保存失败，请稍后重试。', 'Saving the treatment line failed. Please try again later.'),
      editParse: text('这次内容没有被识别为对当前病历的修改。如果是整份新病史，请点“作为新病历提取”。', 'This was not recognized as an edit to the current record. For a full new history, choose "Extract as New Record".'),
      editSave: text('修改已解析，但保存失败，请稍后重试。', 'The edit was parsed, but saving failed. Please try again later.'),
      editRequest: text('模型暂时没有返回可用修改，请测试服务连通性后重试。', 'The model did not return a usable edit. Test provider connectivity and retry.'),
    },
  },
  timeline: {
    tableTitle: text('病历预览', 'Record Preview'),
    basicInfoTitle: text('基本信息', 'Basic Information'),
    basicInfoSubtitle: text('基础信息区块', 'Basic Info Block'),
    criticalFields: text('关键字段：肿瘤类型 / 分期 / 治疗方案', 'Critical Fields: Tumor Type / Stage / Regimen'),
    gender: text('性别', 'Gender'),
    age: text('年龄', 'Age'),
    height: text('身高', 'Height'),
    weight: text('体重', 'Weight'),
    bmi: text('BMI', 'BMI'),
    tumorType: text('肿瘤类型', 'Tumor Type'),
    diagnosisDate: text('诊断日期', 'Diagnosis Date'),
    stage: text('分期', 'Stage'),
    initialOnsetTitle: text('初发区块', 'Initial Onset'),
    regimen: text('治疗方案', 'Regimen'),
    triggerDate: text('初发时间', 'Trigger Date'),
    immunohistochemistry: text('免疫组化', 'Immunohistochemistry'),
    genetic: text('基因检测', 'Genetic Analysis'),
    treatmentLine: text('治疗线', 'Line'),
    startDate: text('开始时间', 'Start Date'),
    endDate: text('结束时间', 'End Date'),
    biopsy: text('活检', 'Biopsy'),
    emptyTitle: text('尚未生成初发区块或治疗线。', 'No initial onset block or treatment lines yet.'),
    emptyBody: text('提交患者描述后，这里会按病程资料自动组织布局，并对关键缺失字段做高亮提示。', 'After you submit the patient narrative, this area will organize the timeline from clinical-course data and highlight critical missing fields.'),
    emptyStateKey: text('时间线状态', 'Timeline State'),
    tableKey: text('时间线表格', 'Timeline Table'),
    initialOnsetSubtitle: text('初发', 'Initial Onset'),
    treatmentLineSubtitle: text('治疗线', 'Treatment Line'),
  },
  workspaceShell: {
    footerProtocol: text('协议：临床 ALPHA-01 // 无未匹配数据', 'Protocol: Clinical ALPHA-01 // No unmatched data'),
  },
  recordPage: {
    dark: {
      initialOnsetTitle: text('初发诊断', 'Initial Onset'),
      initialOnsetDiagnosis: text('非小细胞肺癌', 'Non-Small Cell Lung Cancer'),
      initialOnsetSummary: text('患者于 2023 年 4 月因持续性咳嗽及胸痛就诊。CT 检查显示左上肺占位性病变（3.2cm x 2.8cm），伴有纵隔淋巴结肿大。活检病理确认为肺腺癌。', 'The patient presented in April 2023 with persistent cough and chest pain. CT showed a left upper lung mass (3.2cm x 2.8cm) with mediastinal lymphadenopathy. Biopsy pathology confirmed lung adenocarcinoma.'),
      immunohistochemistry: text('免疫组化', 'Immunohistochemistry'),
      geneticAnalysis: text('基因检测', 'Genetic Analysis'),
      line1Title: text('一线治疗', 'Line 01'),
      line1Badge: text('阶段完成', 'Phase Completed'),
      line1Therapy: text('奥希替尼靶向治疗', 'Osimertinib Targeted Therapy'),
      line1Summary: text('患者开始接受第三代 EGFR-TKI 治疗。初始反应良好，肿瘤体积缩小约 40%。治疗 9 个月后，复查显示左肺病灶增大，并出现微小脑转移灶，判定为疾病进展。', 'The patient started third-generation EGFR-TKI therapy with a strong initial response, shrinking the tumor by about 40%. After 9 months, follow-up imaging showed enlargement of the left lung lesion and small brain metastases, indicating disease progression.'),
      resistanceAnalysis: text('耐药分析', 'Resistance Analysis'),
      resistanceBody: text('检测到 EGFR T790M 突变消失，伴随 MET 基因扩增（FISH 阳性）。', 'EGFR T790M loss was detected together with MET amplification (FISH positive).'),
      line2Title: text('二线治疗', 'Line 02'),
      line2Badge: text('进行中', 'In Progress'),
      line2Therapy: text('培美曲塞 + 卡铂 + 赛沃替尼', 'Pemetrexed + Carboplatin + Savolitinib'),
      line2Summary: text('针对 MET 扩增，调整方案为化疗联合 MET 抑制剂治疗。目前已完成 4 个周期。患者自述呼吸困难症状缓解，脑部病灶稳定。', 'For MET amplification, the regimen was adjusted to chemotherapy plus a MET inhibitor. Four cycles have been completed, with improved dyspnea and stable brain lesions.'),
      aiConfidenceLog: text('AI 置信记录', 'AI Confidence Log'),
      matchScore: text('方案匹配度：94.2%', 'Regimen Match: 94.2%'),
      stabilityIndex: text('稳定性指标', 'Stability Index'),
      stabilityValue: text('稳定预期', 'Stable Predicted'),
      prognosisValue: text('预后偏乐观', 'Prognosis Optimistic'),
      verificationStamp: text('核验标记', 'Verification Stamp'),
      verificationBody: text('此档案由萤屿临床 AI 自动提取并结构化。所有数据点均经过病理报告与影像诊断交叉验证。', 'This archive is automatically extracted and structured by Firefly Isle Clinical AI. Every data point is cross-checked against pathology and imaging evidence.'),
      authorizedSystem: text('授权系统', 'Authorized System'),
      scrollAudit: text('滚动审阅', 'Scroll to Audit'),
    },
    light: {
      archive: text('病历档案', 'The Archive'),
      recordId: text('档案编号', 'Record ID'),
      lastUpdated: text('最后更新：2023.10.15', 'Last Updated: 2023.10.15'),
      reportRail: text('时间顺序报告', 'Chronological Report'),
      initialOnsetTitle: text('初发诊断', 'Initial Onset'),
      initialOnsetBody: text('患者于2021年10月因持续性干咳就诊。胸部CT显示左肺下叶占位，大小约 3.2 x 2.8 cm，伴纵隔淋巴结肿大。纤维支气管镜活检确诊为肺腺癌。病理分期定为 T2aN2M0 (IIIA期)。', 'The patient presented in October 2021 with persistent dry cough. Chest CT showed a left lower lobe mass about 3.2 x 2.8 cm with mediastinal lymphadenopathy. Bronchoscopic biopsy confirmed lung adenocarcinoma, staged as T2aN2M0 (stage IIIA).'),
      initialOnsetQuote: text('“诊断过程伴随显著体重减轻，患者自述伴有阵发性胸痛。”', '"The diagnostic course included marked weight loss, and the patient reported intermittent chest pain."'),
      ihcMarkers: text('IHC 标记', 'IHC Markers'),
      line1Title: text('一线治疗', 'Line 01'),
      geneticData: text('基因数据', 'Genetic Data'),
      geneticSubtitle: text('检测到 19 外显子缺失', 'Exon 19 Deletion Detected'),
      protocol: text('治疗方案', 'Protocol'),
      protocolSubtitle: text('80mg 每日一次，口服', '80mg qd, Oral'),
      line1Body: text('基因检测提示EGFR 19号外显子缺失。患者开始接受第三代TKI奥希替尼治疗。初期疗效评价为PR（部分缓解），肿瘤缩小40%以上。治疗期间耐受良好，主要副作用为I级皮疹及偶发腹泻，均在可控范围内。', 'Genetic testing identified an EGFR exon 19 deletion. The patient started third-generation TKI therapy with osimertinib and achieved a partial response with more than 40% tumor shrinkage. Tolerance remained good, with only grade 1 rash and occasional diarrhea.'),
      line2Title: text('二线治疗', 'Line 02'),
      resistanceDetected: text('已检测到耐药', 'Resistance Detected'),
      line2Body: text('2023年7月随访发现疾病进展（PD），左肺原发灶增大，并出现多发骨转移（肋骨、椎体）。进行二次活检及液体活检，未发现T790M突变，提示复杂的耐药机制，可能涉及c-MET扩增。', 'Follow-up in July 2023 showed progression with enlargement of the primary left lung lesion and multiple bone metastases in the ribs and vertebrae. Repeat tissue and liquid biopsy found no T790M mutation, suggesting a complex resistance mechanism that may involve c-MET amplification.'),
      newPlan: text('新方案拟定', 'New Plan'),
      newPlanBody: text('联合抗血管生成治疗以应对骨转移风险。', 'Anti-angiogenic combination therapy was selected to address bone metastasis risk.'),
      riskWarning: text('风险提示', 'Risk Warning'),
      verification: text('核验说明', 'Verification'),
      verificationBody: text('此报告由一页萤屿临床 AI 系统根据原始病历扫描件及病理报告自动生成。结构化数据已通过三级审核。所有临床决策须由主治医师最终确认。', 'This report is automatically generated by Firefly Isle Clinical AI from original scans and pathology reports. Structured data has passed three review stages. All clinical decisions must be confirmed by the attending physician.'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      editData: text('修正数据', 'Edit Data'),
      copyright: text('© 2024 临床智能档案。保留所有权利。', '© 2024 Clinical Intelligence Archive. All rights reserved.'),
    },
  },
  record: {
    dark: {
      archiveNode: text('档案节点：', 'Archive Node: '),
      title: text('临床病史档案', 'Clinical Record Archive'),
      initialOnset: text('初发诊断', 'Initial Onset'),
      line1: text('一线治疗', 'Line 01'),
      line2: text('二线治疗', 'Line 02'),
      completed: text('阶段完成', 'Phase Completed'),
      inProgress: text('进行中', 'In Progress'),
      resistanceAnalysis: text('耐药分析', 'Resistance Analysis'),
      confidenceLog: text('AI 置信记录', 'AI Confidence Log'),
      stabilityIndex: text('稳定性指标', 'Stability Index'),
      verificationStamp: text('核验标记：', 'Verification Stamp:'),
      verificationBody: text('此档案由萤屿临床 AI 自动提取并结构化。所有数据点均经过病理报告与影像诊断交叉验证。', 'This archive is automatically extracted and structured by Firefly Isle Clinical AI. Every data point is cross-checked against pathology and imaging evidence.'),
      authorizedSystem: text('授权系统', 'Authorized System'),
      scrollAudit: text('滚动审阅', 'Scroll to Audit'),
      subjectId: text('受试者编号', 'Subject ID'),
      creationDate: text('创建日期', 'Creation Date'),
      securityProtocol: text('安全协议', 'Security Protocol'),
      dataNode: text('数据节点', 'Data Node'),
      age: text('年龄', 'Age'),
      bloodType: text('血型', 'Blood Type'),
      height: text('身高', 'Height'),
      weight: text('体重', 'Weight'),
      ihc: text('免疫组化', 'Immunohistochemistry'),
      genetic: text('基因检测', 'Genetic Analysis'),
    },
    light: {
      archiveNode: text('档案节点', 'Archive Node'),
      archiveTitle: text('临床病史档案', 'Clinical Record Archive'),
      patientName: text('陈先生', 'Mr. Chen'),
      patientSummary: text('男性 / 64 岁', 'Male / 64 Years'),
      archive: text('病历档案', 'The Archive'),
      age: text('年龄', 'Age'),
      bloodType: text('血型', 'Blood Type'),
      height: text('身高', 'Height'),
      weight: text('体重', 'Weight'),
      recordId: text('档案编号：', 'Record ID: '),
      lastUpdated: text('最后更新：2023.10.15', 'Last Updated: 2023.10.15'),
      reportRail: text('时间顺序报告', 'Chronological Report'),
      initialOnset: text('初发诊断', 'Initial Onset'),
      line1: text('一线治疗', 'Line 01'),
      line2: text('二线治疗', 'Line 02'),
      ihcMarkers: text('IHC 标记', 'IHC Markers'),
      geneticData: text('基因数据', 'Genetic Data'),
      protocol: text('治疗方案', 'Protocol'),
      resistanceDetected: text('已检测到耐药', 'Resistance Detected'),
      newPlan: text('新方案拟定', 'New Plan'),
      riskWarning: text('风险提示', 'Risk Warning'),
      verification: text('核验说明', 'Verification'),
      verificationBody: text('此报告由一页萤屿临床 AI 系统根据原始病历扫描件及病理报告自动生成。结构化数据已通过三级审核。所有临床决策须由主治医师最终确认。', 'This report is automatically generated by Firefly Isle Clinical AI from original scans and pathology reports. Structured data has passed three review stages. All clinical decisions must be confirmed by the attending physician.'),
      exportPdf: text('导出 PDF', 'Export PDF'),
      editData: text('修正数据', 'Edit Data'),
      copyright: text('© 2024 临床智能档案。保留所有权利。', '© 2024 Clinical Intelligence Archive. All rights reserved.'),
    },
  },
} as const

export function getCopy<T extends LocaleText>(value: T, locale: Locale) {
  return value[locale]
}
